export const menu_data = [
    {
      id: "0",
      code: "AC-2618",
      title: "My Kpi",
      description: "Kpi Description",
      date: "2023-11-14",
      type: "kpi",
      link: "/kpi-overview",
      color: "dark",
    },
    {
      id: "1",
      code: "AC-5655",
      title: "Goal 1",
      description: "Account Creation Module",
      date: "2023-11-12",
      type: "goal",
      link: "/goal-overview",
      color: "dark",
    },
    {
      id: "2",
      code: "AC-3343",
      title: "My Goal Title",
      description: "Account Creation Module",
      date: "2023-11-02",
      type: "goal",
      link: "/goal-overview",
      color: "dark",
    },
    {
      id: "3",
      code: "AC-1234",
      title: "My Project 1",
      description: "Final changes uploaded and tested all the changes",
      date: "2023-10-25",
      type: "project",
      link: "/project-overview",
      color: "light",
    },
    {
      id: "4",
      code: "AC-1234",
      title: "My Task 1",
      description: "Final changes uploaded and tested all the changes",
      date: "2023-10-25",
      type: "task",
      link: "/tasks-overview",
      color: "light",
    },
    {
      id: "5",
      code: "AC-1234",
      title: "My Subtask 1",
      description: "Final changes uploaded and tested all the changes",
      date: "2023-10-25",
      type: "subtask",
      link: "/subtasks-overview",
      color: "light",
    },
  ];