export const data = [
  {
    id: "0",
    name: "Research and development",
    color: "#004225",
    type: "department",
    description: "",
    overview: "no",
    section: "1",
    children: [
      {
        id: "0-0",
        name: "Goals",
        color: "#005831",
        type: "goal",
        description: "",
        overview: "no",
        section: "2",
        children: [
          {
            id: "0-0-0",
            name: "Goal 1",
            color: "#006e3e",
            type: "goal-content",
            description: "",
            overview: "yes",
            section: "3",
            children: [
              {
                id: "0-0-0-0",
                name: "KPIs",
                color: "#00854a",
                type: "kpi",
                description: "",
                overview: "no",
                section: "4",
                children: [
                  {
                    id: "0-0-0-0-0",
                    name: "KPI 1",
                    color: "#009b57",
                    type: "kpi-content",
                    description: "",
                    overview: "yes",
                    section: "5",
                    children: [
                      {
                        id: "0-0-0-0-0-0",
                        name: "Projects",
                        color: "#00b163",
                        type: "project",
                        description: "",
                        overview: "no",
                        section: "6",
                        children: [
                          {
                            id: "0-0-0-0-0-0-0",
                            name: "Project 1",
                            color: "#00c770",
                            type: "project-content",
                            description: "",
                            overview: "yes",
                            section: "7",
                            children: [
                              {
                                id: "0-0-0-0-0-0-0-0",
                                name: "Task",
                                color: "#00dd7c",
                                type: "task",
                                description: "",
                                overview: "no",
                                section: "8",
                                children: [
                                  {
                                    id: "0-0-0-0-0-0-0-0-0",
                                    name: "Task 1",
                                    color: "#00dd7c",
                                    type: "task-content",
                                    description: "",
                                    overview: "yes",
                                    section: "9",
                                    children: [
                                      {
                                        id: "0-0-0-0-0-0-0-0-0-0",
                                        name: "Subtasks",
                                        color: "#0bff94",
                                        type: "subtask",
                                        description: "",
                                        overview: "no",
                                        section: "10",
                                        children: [
                                          {
                                            id: "0-0-0-0-0-0-0-0-0-0-0",
                                            name: "Subtask 1",
                                            color: "#21ff9d",
                                            type: "subtask-content",
                                            description: "",
                                            overview: "yes",
                                            section: "11",
                                            children: [
                                              {
                                                id: "0-0-0-0-0-0-0-0-0-0-0-0",
                                                name: "docx_file.docx",
                                                color: "#c7df19",
                                                type: "subtask-file",
                                                description: "",
                                                overview: "yes",
                                                section: "12",
                                              },
                                              {
                                                id: "0-0-0-0-0-0-0-0-0-0-0-1",
                                                name: "excel_file.xlsx",
                                                color: "#c7df19",
                                                type: "subtask-file",
                                                description: "",
                                                overview: "yes",
                                                section: "12",
                                              },
                                              {
                                                id: "0-0-0-0-0-0-0-0-0-0-0-2",
                                                name: "img_file.png",
                                                color: "#c7df19",
                                                type: "subtask-file",
                                                description: "",
                                                overview: "yes",
                                                section: "12",
                                              },
                                              {
                                                id: "0-0-0-0-0-0-0-0-0-0-0-3",
                                                name: "pdf_file.pdf",
                                                color: "#c7df19",
                                                type: "subtask-file",
                                                description: "",
                                                overview: "yes",
                                                section: "12",
                                              },
                                            ],
                                          },
                                        ],
                                      },
                                    ],
                                  },
                                ],
                              },
                              {
                                id: "0-0-0-0-0-0-0-1",
                                name: "Content",
                                color: "#00dd7c",
                                type: "content",
                                description: "",
                                overview: "no",
                                section: "8",
                              },
                              {
                                id: "0-0-0-0-0-0-0-2",
                                name: "docx_file.docx",
                                color: "#c7df19",
                                type: "project-file",
                                description: "",
                                overview: "yes",
                                section: "8",
                              },
                              {
                                id: "0-0-0-0-0-0-0-3",
                                name: "excel_file.xlsx",
                                color: "#c7df19",
                                type: "project-file",
                                description: "",
                                overview: "yes",
                                section: "8",
                              },
                            ],
                          },
                          {
                            id: "0-0-0-0-0-0-1",
                            name: "Project 2",
                            color: "#00c770",
                            type: "project-content",
                            description: "",
                            overview: "yes",
                            section: "7",
                          },
                        ],
                      },
                    ],
                  },
                  {
                    id: "0-0-0-0-1",
                    name: "KPI 2",
                    color: "#009b57",
                    type: "kpi-content",
                    description: "",
                    overview: "yes",
                    section: "5",
                  },
                  {
                    id: "0-0-0-0-2",
                    name: "KPI 3",
                    color: "#009b57",
                    type: "kpi-content",
                    description: "",
                    overview: "yes",
                    section: "5",
                  },
                ],
              },
            ],
          },
          {
            id: "0-0-1",
            name: "Goal 2",
            color: "#006e3e",
            type: "goal-content",
            description: "",
            overview: "yes",
            section: "3",
          },
          {
            id: "0-0-2",
            name: "Goal 3",
            color: "#006e3e",
            type: "goal-content",
            description: "",
            overview: "yes",
            section: "3",
          },
        ],
      },
      {
        id: "0-1",
        name: "KPIs",
        color: "#005831",
        type: "kpi",
        description: "",
        overview: "no",
        section: "2",
        children: [
          {
            id: "0-1-0",
            name: "KPI 1",
            color: "#006e3e",
            type: "kpi-content",
            description: "",
            overview: "yes",
            section: "3",
            children: [
              {
                id: "0-1-0-0",
                name: "Projects",
                color: "#00854a",
                type: "project",
                description: "",
                overview: "no",
                section: "4",
                children: [
                  {
                    id: "0-1-0-0-0",
                    name: "Project 1",
                    color: "#009b57",
                    type: "project-content",
                    description: "",
                    overview: "yes",
                    section: "5",
                    children: [
                      {
                        id: "0-1-0-0-0-0",
                        name: "Task",
                        color: "#00b163",
                        type: "task",
                        description: "",
                        overview: "no",
                        section: "6",
                        children: [
                          {
                            id: "0-1-0-0-0-0-0",
                            name: "Task 1",
                            color: "#00c770",
                            type: "task-content",
                            description: "",
                            overview: "yes",
                            section: "7",
                            children: [
                              {
                                id: "0-1-0-0-0-0-0-0",
                                name: "Subtasks",
                                color: "#00dd7c",
                                type: "subtask",
                                description: "",
                                overview: "no",
                                section: "8",
                                children: [
                                  {
                                    id: "0-1-0-0-0-0-0-0-0",
                                    name: "Subtask 1",
                                    color: "#00dd7c",
                                    type: "subtask-content",
                                    description: "",
                                    overview: "yes",
                                    section: "9",
                                    children: [
                                      {
                                        id: "0-1-0-0-0-0-0-0-0-0",
                                        name: "docx_file.docx",
                                        color: "#c7df19",
                                        type: "subtask-file",
                                        description: "",
                                        overview: "yes",
                                        section: "10",
                                      },
                                      {
                                        id: "0-1-0-0-0-0-0-0-0-1",
                                        name: "excel_file.xlsx",
                                        color: "#c7df19",
                                        type: "subtask-file",
                                        description: "",
                                        overview: "yes",
                                        section: "10",
                                      },
                                      {
                                        id: "0-1-0-0-0-0-0-0-0-2",
                                        name: "img_file.png",
                                        color: "#c7df19",
                                        type: "subtask-file",
                                        description: "",
                                        overview: "yes",
                                        section: "10",
                                      },
                                      {
                                        id: "0-1-0-0-0-0-0-0-0-3",
                                        name: "pdf_file.pdf",
                                        color: "#c7df19",
                                        type: "subtask-file",
                                        description: "",
                                        overview: "yes",
                                        section: "10",
                                      },
                                    ],
                                  },
                                ],
                              },
                            ],
                          },
                        ],
                      },
                      {
                        id: "0-1-0-0-0-1",
                        name: "Content",
                        color: "#00b163",
                        type: "content",
                        description: "",
                        overview: "no",
                        section: "6",
                      },
                      {
                        id: "0-1-0-0-0-2",
                        name: "docx_file.docx",
                        color: "#c7df19",
                        type: "project-file",
                        description: "",
                        overview: "yes",
                        section: "6",
                      },
                      {
                        id: "0-1-0-0-0-3",
                        name: "excel_file.xlsx",
                        color: "#c7df19",
                        type: "project-file",
                        description: "",
                        overview: "yes",
                        section: "6",
                      },
                    ],
                  },
                  {
                    id: "0-1-0-0-1",
                    name: "Project 2",
                    color: "#009b57",
                    type: "project-content",
                    description: "",
                    overview: "yes",
                    section: "5",
                  },
                ],
              },
            ],
          },
          {
            id: "0-1-1",
            name: "KPI 2",
            color: "#006e3e",
            type: "kpi-content",
            description: "",
            overview: "yes",
            section: "3",
          },
          {
            id: "0-1-2",
            name: "KPI 3",
            color: "#006e3e",
            type: "kpi-content",
            description: "",
            overview: "yes",
            section: "3",
          },
        ],
      },
      {
        id: "0-2",
        name: "Projects",
        color: "#005831",
        type: "project",
        description: "",
        overview: "no",
        section: "2",
        children: [
          {
            id: "0-2-0",
            name: "Project 1",
            color: "#006e3e",
            type: "project-content",
            description: "",
            overview: "yes",
            section: "3",
            children: [
              {
                id: "0-2-0-0",
                name: "Task",
                color: "#00854a",
                type: "task",
                description: "",
                overview: "no",
                section: "4",
                children: [
                  {
                    id: "0-2-0-0-0",
                    name: "Task 1",
                    color: "#009b57",
                    type: "task-content",
                    description: "",
                    overview: "yes",
                    section: "5",
                    children: [
                      {
                        id: "0-2-0-0-0-0",
                        name: "Subtasks",
                        color: "#00b163",
                        type: "subtask",
                        description: "",
                        overview: "no",
                        section: "6",
                        children: [
                          {
                            id: "0-2-0-0-0-0-0",
                            name: "Subtask 1",
                            color: "#00c770",
                            type: "subtask-content",
                            description: "",
                            overview: "yes",
                            section: "7",
                            children: [
                              {
                                id: "0-2-0-0-0-0-0-0",
                                name: "docx_file.docx",
                                color: "#c7df19",
                                type: "subtask-file",
                                description: "",
                                overview: "yes",
                                section: "8",
                              },
                              {
                                id: "0-2-0-0-0-0-0-1",
                                name: "excel_file.xlsx",
                                color: "#c7df19",
                                type: "subtask-file",
                                description: "",
                                overview: "yes",
                                section: "8",
                              },
                              {
                                id: "0-2-0-0-0-0-0-2",
                                name: "img_file.png",
                                color: "#c7df19",
                                type: "subtask-file",
                                description: "",
                                overview: "yes",
                                section: "8",
                              },
                              {
                                id: "0-2-0-0-0-0-0-3",
                                name: "pdf_file.pdf",
                                color: "#c7df19",
                                type: "subtask-file",
                                description: "",
                                overview: "yes",
                                section: "8",
                              },
                            ],
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
              {
                id: "0-2-0-1",
                name: "Content",
                color: "#00854a",
                type: "content",
                description: "",
                overview: "no",
                section: "4",
              },
              {
                id: "0-2-0-2",
                name: "docx_file.docx",
                color: "#c7df19",
                type: "project-file",
                description: "",
                overview: "yes",
                section: "4",
              },
              {
                id: "0-2-0-3",
                name: "excel_file.xlsx",
                color: "#c7df19",
                type: "project-file",
                description: "",
                overview: "yes",
                section: "4",
              },
            ],
          },
          {
            id: "0-2-1",
            name: "Project 2",
            color: "#006e3e",
            type: "project-content",
            description: "",
            overview: "yes",
            section: "3",
          },
        ],
      },
      {
        id: "0-3",
        name: "Tasks",
        color: "#005831",
        type: "task",
        description: "",
        overview: "no",
        section: "2",
        children: [
          {
            id: "0-3-0",
            name: "Task 1",
            color: "#006e3e",
            type: "task-content",
            description: "",
            overview: "yes",
            section: "3",
            children: [
              {
                id: "0-3-0-0",
                name: "Subtasks",
                color: "#00854a",
                type: "subtask",
                description: "",
                overview: "no",
                section: "4",
                children: [
                  {
                    id: "0-3-0-0-0",
                    name: "Subtask 1",
                    color: "#009b57",
                    type: "subtask-content",
                    description: "",
                    overview: "yes",
                    section: "5",
                    children: [
                      {
                        id: "0-3-0-0-0-0",
                        name: "docx_file.docx",
                        color: "#c7df19",
                        type: "subtask-file",
                        description: "",
                        overview: "yes",
                        section: "6",
                      },
                      {
                        id: "0-3-0-0-0-1",
                        name: "excel_file.xlsx",
                        color: "#c7df19",
                        type: "subtask-file",
                        description: "",
                        overview: "yes",
                        section: "6",
                      },
                      {
                        id: "0-3-0-0-0-2",
                        name: "img_file.png",
                        color: "#c7df19",
                        type: "subtask-file",
                        description: "",
                        overview: "yes",
                        section: "6",
                      },
                      {
                        id: "0-3-0-0-0-3",
                        name: "pdf_file.pdf",
                        color: "#c7df19",
                        type: "subtask-file",
                        description: "",
                        overview: "yes",
                        section: "6",
                      },
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "0-4",
        name: "Subtasks",
        color: "#005831",
        type: "subtask",
        description: "",
        overview: "no",
        section: "2",
        children: [
          {
            id: "0-4-0",
            name: "Subtask 1",
            color: "#006e3e",
            type: "subtask-content",
            description: "",
            overview: "yes",
            section: "3",
            children: [
              {
                id: "0-4-0-0",
                name: "docx_file.docx",
                color: "#c7df19",
                type: "subtask-file",
                description: "",
                overview: "yes",
                section: "4",
              },
              {
                id: "0-4-0-1",
                name: "excel_file.xlsx",
                color: "#c7df19",
                type: "subtask-file",
                description: "",
                overview: "yes",
                section: "4",
              },
              {
                id: "0-4-0-2",
                name: "img_file.png",
                color: "#c7df19",
                type: "subtask-file",
                description: "",
                overview: "yes",
                section: "4",
              },
              {
                id: "0-4-0-3",
                name: "pdf_file.pdf",
                color: "#c7df19",
                type: "subtask-file",
                description: "",
                overview: "yes",
                section: "4",
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "1",
    name: "Marketing and sales",
    color: "#004225",
    type: "department",
    description: "",
    overview: "no",
    section: "1",
    children: [
      {
        id: "1-0",
        name: "Goals",
        color: "#005831",
        type: "goal",
        description: "",
        overview: "no",
        section: "2",
      },
      {
        id: "1-1",
        name: "KPIs",
        color: "#005831",
        type: "kpi",
        description: "",
        overview: "no",
        section: "2",
      },
      {
        id: "1-2",
        name: "Projects",
        color: "#005831",
        type: "project",
        description: "",
        overview: "no",
        section: "2",
      },
      {
        id: "1-3",
        name: "Tasks",
        color: "#005831",
        type: "task",
        description: "",
        overview: "no",
        section: "2",
      },
      {
        id: "1-4",
        name: "Subtasks",
        color: "#005831",
        type: "subtask",
        description: "",
        overview: "no",
        section: "2",
      },
    ],
  },
  {
    id: "2",
    name: "Human resources",
    color: "#004225",
    type: "department",
    description: "",
    overview: "no",
    section: "1",
    children: [
      {
        id: "2-0",
        name: "Goals",
        color: "#005831",
        type: "goal",
        description: "",
        overview: "no",
        section: "2",
      },
      {
        id: "2-1",
        name: "KPIs",
        color: "#005831",
        type: "kpi",
        description: "",
        overview: "no",
        section: "2",
      },
      {
        id: "2-2",
        name: "Projects",
        color: "#005831",
        type: "project",
        description: "",
        overview: "no",
        section: "2",
      },
      {
        id: "2-3",
        name: "Tasks",
        color: "#005831",
        type: "task",
        description: "",
        overview: "no",
        section: "2",
      },
      {
        id: "2-4",
        name: "Subtasks",
        color: "#005831",
        type: "subtask",
        description: "",
        overview: "no",
        section: "2",
      },
    ],
  },
  {
    id: "3",
    name: "Customer service",
    color: "#004225",
    type: "department",
    description: "",
    overview: "no",
    section: "1",
    children: [
      {
        id: "3-0",
        name: "Goals",
        color: "#005831",
        type: "goal",
        description: "",
        overview: "no",
        section: "2",
      },
      {
        id: "3-1",
        name: "KPIs",
        color: "#005831",
        type: "kpi",
        description: "",
        overview: "no",
        section: "2",
      },
      {
        id: "3-2",
        name: "Projects",
        color: "#005831",
        type: "project",
        description: "",
        overview: "no",
        section: "2",
      },
      {
        id: "3-3",
        name: "Tasks",
        color: "#005831",
        type: "task",
        description: "",
        overview: "no",
        section: "2",
      },
      {
        id: "3-4",
        name: "Subtasks",
        color: "#005831",
        type: "subtask",
        description: "",
        overview: "no",
        section: "2",
      },
    ],
  },
];
