export const data = [
    {
      id: "0",
      name: "Research and development",
      color: "#004225",
      type: "department",
      overview: "no",
      section: "1",
      children: [
        {
          id: "0-0",
          name: "Goals",
          color: "#005831",
          type: "goal",
          overview: "no",
          section: "2",
          children: [
            {
              id: "0-0-0",
              name: "Goal 1",
              color: "#006e3e",
              type: "goal-content",
              overview: "yes",
              section: "3",
              children: [
                {
                  id: "0-0-0-0",
                  name: "KPIs",
                  color: "#00854a",
                  type: "kpi",
                  overview: "no",
                  section: "4",
                  children: [
                    {
                      id: "0-0-0-0-0",
                      name: "KPI 1",
                      color: "#009b57",
                      type: "kpi-content",
                      overview: "yes",
                      section: "5",
                      children: [
                        {
                          id: "0-0-0-0-0-0",
                          name: "Projects",
                          color: "#00b163",
                          type: "project",
                          overview: "no",
                          section: "6",
                          children: [
                            {
                              id: "0-0-0-0-0-0-0",
                              name: "Project 1",
                              color: "#00c770",
                              type: "project-content",
                              overview: "yes",
                              section: "7",
                              children: [
                                {
                                  id: "0-0-0-0-0-0-0-0",
                                  name: "Task",
                                  color: "#00dd7c",
                                  type: "task",
                                  overview: "no",
                                  section: "8",
                                  children: [
                                    {
                                      id: "0-0-0-0-0-0-0-0-0",
                                      name: "Task 1",
                                      color: "#00dd7c",
                                      type: "task-content",
                                      overview: "yes",
                                      section: "9",
                                      children: [
                                        {
                                          id: "0-0-0-0-0-0-0-0-0-0",
                                          name: "Subtasks",
                                          color: "#0bff94",
                                          type: "subtask",
                                          overview: "no",
                                          section: "10",
                                          children: [
                                            {
                                              id: "0-0-0-0-0-0-0-0-0-0-0",
                                              name: "Subtask 1",
                                              color: "#21ff9d",
                                              type: "subtask-content",
                                              overview: "yes",
                                              section: "11",
                                              children: [
                                                {
                                                  id: "0-0-0-0-0-0-0-0-0-0-0-0",
                                                  name: "file1.txt",
                                                  color: "#c7df19",
                                                  type: "subtask-file",
                                                  overview: "yes",
                                                  section: "12",
                                                },
                                                {
                                                  id: "0-0-0-0-0-0-0-0-0-0-0-1",
                                                  name: "file2.txt",
                                                  color: "#c7df19",
                                                  type: "subtask-file",
                                                  overview: "yes",
                                                  section: "12",
                                                },
                                                {
                                                  id: "0-0-0-0-0-0-0-0-0-0-0-2",
                                                  name: "file3.txt",
                                                  color: "#c7df19",
                                                  type: "subtask-file",
                                                  overview: "yes",
                                                  section: "12",
                                                },
                                              ],
                                            },
                                          ],
                                        },
                                      ],
                                    },
                                  ],
                                },
                                {
                                  id: "0-0-0-0-0-0-0-1",
                                  name: "Content",
                                  color: "#00dd7c",
                                  type: "content",
                                  overview: "no",
                                  section: "8",
                                },
                                {
                                  id: "0-0-0-0-0-0-0-2",
                                  name: "project-file-1.jpg",
                                  color: "#c7df19",
                                  type: "project-file",
                                  overview: "yes",
                                  section: "8",
                                },
                                {
                                  id: "0-0-0-0-0-0-0-3",
                                  name: "project-file-2.jpg",
                                  color: "#c7df19",
                                  type: "project-file",
                                  overview: "yes",
                                  section: "8",
                                },
                              ],
                            },
                            {
                              id: "0-0-0-0-0-0-1",
                              name: "Project 2",
                              color: "#00c770",
                              type: "project-content",
                              overview: "yes",
                              section: "7",
                            },
                          ],
                        },
                      ],
                    },
                    {
                      id: "0-0-0-0-1",
                      name: "KPI 2",
                      color: "#009b57",
                      type: "kpi-content",
                      overview: "yes",
                      section: "5",
                    },
                    {
                      id: "0-0-0-0-2",
                      name: "KPI 3",
                      color: "#009b57",
                      type: "kpi-content",
                      overview: "yes",
                      section: "5",
                    },
                  ],
                },
              ],
            },
            {
              id: "0-0-1",
              name: "Goal 2",
              color: "#006e3e",
              type: "goal-content",
              overview: "yes",
              section: "3",
            },
            {
              id: "0-0-2",
              name: "Goal 3",
              color: "#006e3e",
              type: "goal-content",
              overview: "yes",
              section: "3",
            },
          ],
        },
        {
          id: "0-1",
          name: "KPIs",
          color: "#005831",
          type: "kpi",
          overview: "no",
          section: "2",
          children: [
            {
              id: "0-1-0",
              name: "KPI 1",
              color: "#006e3e",
              type: "kpi-content",
              overview: "yes",
              section: "3",
              children: [
                {
                  id: "0-1-0-0",
                  name: "Projects",
                  color: "#00854a",
                  type: "project",
                  overview: "no",
                  section: "4",
                  children: [
                    {
                      id: "0-1-0-0-0",
                      name: "Project 1",
                      color: "#009b57",
                      type: "project-content",
                      overview: "yes",
                      section: "5",
                      children: [
                        {
                          id: "0-1-0-0-0-0",
                          name: "Task",
                          color: "#00b163",
                          type: "task",
                          overview: "no",
                          section: "6",
                          children: [
                            {
                              id: "0-1-0-0-0-0-0",
                              name: "Task 1",
                              color: "#00c770",
                              type: "task-content",
                              overview: "yes",
                              section: "7",
                              children: [
                                {
                                  id: "0-1-0-0-0-0-0-0",
                                  name: "Subtasks",
                                  color: "#00dd7c",
                                  type: "subtask",
                                  overview: "no",
                                  section: "8",
                                  children: [
                                    {
                                      id: "0-1-0-0-0-0-0-0-0",
                                      name: "Subtask 1",
                                      color: "#00dd7c",
                                      type: "subtask-content",
                                      overview: "yes",
                                      section: "9",
                                      children: [
                                        {
                                          id: "0-1-0-0-0-0-0-0-0-0",
                                          name: "file1.txt",
                                          color: "#c7df19",
                                          type: "subtask-file",
                                          overview: "yes",
                                          section: "10",
                                        },
                                        {
                                          id: "0-1-0-0-0-0-0-0-0-1",
                                          name: "file2.txt",
                                          color: "#c7df19",
                                          type: "subtask-file",
                                          overview: "yes",
                                          section: "10",
                                        },
                                        {
                                          id: "0-1-0-0-0-0-0-0-0-2",
                                          name: "file3.txt",
                                          color: "#c7df19",
                                          type: "subtask-file",
                                          overview: "yes",
                                          section: "10",
                                        },
                                      ],
                                    },
                                  ],
                                },
                              ],
                            },
                          ],
                        },
                        {
                          id: "0-1-0-0-0-1",
                          name: "Content",
                          color: "#00b163",
                          type: "content",
                          overview: "no",
                          section: "6",
                        },
                        {
                          id: "0-1-0-0-0-2",
                          name: "project-file-1.jpg",
                          color: "#c7df19",
                          type: "project-file",
                          overview: "yes",
                          section: "6",
                        },
                        {
                          id: "0-1-0-0-0-3",
                          name: "project-file-2.jpg",
                          color: "#c7df19",
                          type: "project-file",
                          overview: "yes",
                          section: "6",
                        },
                      ],
                    },
                    {
                      id: "0-1-0-0-1",
                      name: "Project 2",
                      color: "#009b57",
                      type: "project-content",
                      overview: "yes",
                      section: "5",
                    },
                  ],
                },
              ],
            },
            {
              id: "0-1-1",
              name: "KPI 2",
              color: "#006e3e",
              type: "kpi-content",
              overview: "yes",
              section: "3",
            },
            {
              id: "0-1-2",
              name: "KPI 3",
              color: "#006e3e",
              type: "kpi-content",
              overview: "yes",
              section: "3",
            },
          ],
        },
        {
          id: "0-2",
          name: "Projects",
          color: "#005831",
          type: "project",
          overview: "no",
          section: "2",
          children: [
            {
              id: "0-2-0",
              name: "Project 1",
              color: "#006e3e",
              type: "project-content",
              overview: "yes",
              section: "3",
              children: [
                {
                  id: "0-2-0-0",
                  name: "Task",
                  color: "#00854a",
                  type: "task",
                  overview: "no",
                  section: "4",
                  children: [
                    {
                      id: "0-2-0-0-0",
                      name: "Task 1",
                      color: "#009b57",
                      type: "task-content",
                      overview: "yes",
                      section: "5",
                      children: [
                        {
                          id: "0-2-0-0-0-0",
                          name: "Subtasks",
                          color: "#00b163",
                          type: "subtask",
                          overview: "no",
                          section: "6",
                          children: [
                            {
                              id: "0-2-0-0-0-0-0",
                              name: "Subtask 1",
                              color: "#00c770",
                              type: "subtask-content",
                              overview: "yes",
                              section: "7",
                              children: [
                                {
                                  id: "0-2-0-0-0-0-0-0",
                                  name: "file1.txt",
                                  color: "#c7df19",
                                  type: "subtask-file",
                                  overview: "yes",
                                  section: "8",
                                },
                                {
                                  id: "0-2-0-0-0-0-0-1",
                                  name: "file2.txt",
                                  color: "#c7df19",
                                  type: "subtask-file",
                                  overview: "yes",
                                  section: "8",
                                },
                                {
                                  id: "0-2-0-0-0-0-0-2",
                                  name: "file3.txt",
                                  color: "#c7df19",
                                  type: "subtask-file",
                                  overview: "yes",
                                  section: "8",
                                },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
                {
                  id: "0-2-0-1",
                  name: "Content",
                  color: "#00854a",
                  type: "content",
                  overview: "no",
                  section: "4",
                },
                {
                  id: "0-2-0-2",
                  name: "project-file-1.jpg",
                  color: "#c7df19",
                  type: "project-file",
                  overview: "yes",
                  section: "4",
                },
                {
                  id: "0-2-0-3",
                  name: "project-file-2.jpg",
                  color: "#c7df19",
                  type: "project-file",
                  overview: "yes",
                  section: "4",
                },
              ],
            },
            {
              id: "0-2-1",
              name: "Project 2",
              color: "#006e3e",
              type: "project-content",
              overview: "yes",
              section: "3",
            },
          ],
        },
        {
          id: "0-3",
          name: "Tasks",
          color: "#005831",
          type: "task",
          overview: "no",
          section: "2",
          children: [
            {
              id: "0-3-0",
              name: "Task 1",
              color: "#006e3e",
              type: "task-content",
              overview: "yes",
              section: "3",
              children: [
                {
                  id: "0-3-0-0",
                  name: "Subtasks",
                  color: "#00854a",
                  type: "subtask",
                  overview: "no",
                  section: "4",
                  children: [
                    {
                      id: "0-3-0-0-0",
                      name: "Subtask 1",
                      color: "#009b57",
                      type: "subtask-content",
                      overview: "yes",
                      section: "5",
                      children: [
                        {
                          id: "0-3-0-0-0-0",
                          name: "file1.txt",
                          color: "#c7df19",
                          type: "subtask-file",
                          overview: "yes",
                          section: "6",
                        },
                        {
                          id: "0-3-0-0-0-1",
                          name: "file2.txt",
                          color: "#c7df19",
                          type: "subtask-file",
                          overview: "yes",
                          section: "6",
                        },
                        {
                          id: "0-3-0-0-0-2",
                          name: "file3.txt",
                          color: "#c7df19",
                          type: "subtask-file",
                          overview: "yes",
                          section: "6",
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          id: "0-4",
          name: "Subtasks",
          color: "#005831",
          type: "subtask",
          overview: "no",
          section: "2",
          children: [
            {
              id: "0-4-0",
              name: "Subtask 1",
              color: "#006e3e",
              type: "subtask-content",
              overview: "yes",
              section: "3",
              children: [
                {
                  id: "0-4-0-0",
                  name: "file1.txt",
                  color: "#c7df19",
                  type: "subtask-file",
                  overview: "yes",
                  section: "4",
                },
                {
                  id: "0-4-0-1",
                  name: "file2.txt",
                  color: "#c7df19",
                  type: "subtask-file",
                  overview: "yes",
                  section: "4",
                },
                {
                  id: "0-4-0-2",
                  name: "file3.txt",
                  color: "#c7df19",
                  type: "subtask-file",
                  overview: "yes",
                  section: "4",
                },
              ],
            },
          ],
        },
      ],
    },
    {
      id: "1",
      name: "Marketing and sales",
      color: "#004225",
      type: "department",
      overview: "no",
      section: "1",
      children: [
        {
          id: "1-0",
          name: "Goals",
          color: "#005831",
          type: "goal",
          overview: "no",
          section: "2",
        },
        {
          id: "1-1",
          name: "KPIs",
          color: "#005831",
          type: "kpi",
          overview: "no",
          section: "2",
        },
        {
          id: "1-2",
          name: "Projects",
          color: "#005831",
          type: "project",
          overview: "no",
          section: "2",
        },
        {
          id: "1-3",
          name: "Tasks",
          color: "#005831",
          type: "task",
          overview: "no",
          section: "2",
        },
        {
          id: "1-4",
          name: "Subtasks",
          color: "#005831",
          type: "subtask",
          overview: "no",
          section: "2",
        },
      ],
    },
    {
      id: "2",
      name: "Human resources",
      color: "#004225",
      type: "department",
      overview: "no",
      section: "1",
      children: [
        {
          id: "2-0",
          name: "Goals",
          color: "#005831",
          type: "goal",
          overview: "no",
          section: "2",
        },
        {
          id: "2-1",
          name: "KPIs",
          color: "#005831",
          type: "kpi",
          overview: "no",
          section: "2",
        },
        {
          id: "2-2",
          name: "Projects",
          color: "#005831",
          type: "project",
          overview: "no",
          section: "2",
        },
        {
          id: "2-3",
          name: "Tasks",
          color: "#005831",
          type: "task",
          overview: "no",
          section: "2",
        },
        {
          id: "2-4",
          name: "Subtasks",
          color: "#005831",
          type: "subtask",
          overview: "no",
          section: "2",
        },
      ],
    },
    {
      id: "3",
      name: "Customer service",
      color: "#004225",
      type: "department",
      overview: "no",
      section: "1",
      children: [
        {
          id: "3-0",
          name: "Goals",
          color: "#005831",
          type: "goal",
          overview: "no",
          section: "2",
        },
        {
          id: "3-1",
          name: "KPIs",
          color: "#005831",
          type: "kpi",
          overview: "no",
          section: "2",
        },
        {
          id: "3-2",
          name: "Projects",
          color: "#005831",
          type: "project",
          overview: "no",
          section: "2",
        },
        {
          id: "3-3",
          name: "Tasks",
          color: "#005831",
          type: "task",
          overview: "no",
          section: "2",
        },
        {
          id: "3-4",
          name: "Subtasks",
          color: "#005831",
          type: "subtask",
          overview: "no",
          section: "2",
        },
      ],
    },
  ];