name: React CI

on:
  push:
    branches:
      - "dev"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
    
    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run build
     
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: decision168-front-dev
          AWS_ACCESS_KEY_ID: AKIA5BVQK2T5YZ7MVF7D
          AWS_SECRET_ACCESS_KEY: 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
          AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
          SOURCE_DIR: 'build'      # optional: defaults to entire repository
